name: Check code quality on pull request

on:
  pull_request:
  workflow_dispatch:

env:
  SONAR_HOST_URL: https://sonarcloud.io
  SONAR_PROJECT_KEY: sonarqube-quality-gate-action

jobs:
  sonar-scan:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Wait quality gate result
        run: sleep 5

      - name: Create a comment with the result
        uses: ./
        id: quality-gate-check
        with:
          sonar-host-url: ${{ secrets.SONAR_HOST_URL }}
          sonar-project-key: ${{ secrets.SONAR_PROJECT_KEY }}
          sonar-token: ${{ secrets.SONAR_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          fail-on-quality-gate-error: true

      - run: |
          echo "${{ steps.quality-gate-check.outputs.project-status }}"
          echo "${{ steps.quality-gate-check.outputs.quality-gate-result }}"
