name: Test actions

on:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: phwt/sonarqube-quality-gate-action@v0
        with:
          sonar-project-key: "test-project"
          sonar-host-url: "https://example.com"
          sonar-token: "no-token"
          github-token: ${{ secrets.GITHUB_TOKEN }}
