name: Test actions

on:
  pull_request:
  workflow_dispatch:

env:
  SONAR_HOST_URL: https://sonarcloud.io
  SONAR_PROJECT_KEY: sonarqube-quality-gate-action

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Create a comment with the result
        uses: ./
        id: initial-quality-gate-check
        with:
          sonar-host-url: ${{ env.SONAR_HOST_URL }}
          sonar-project-key: ${{ env.SONAR_PROJECT_KEY }}
          sonar-token: ${{ secrets.SONAR_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Wait before updating the comment
        run: sleep 5

      - name: Rerun to test the comment update
        uses: ./
        id: quality-gate-check
        with:
          sonar-host-url: ${{ env.SONAR_HOST_URL }}
          sonar-project-key: ${{ env.SONAR_PROJECT_KEY }}
          sonar-token: ${{ secrets.SONAR_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - run: |
          echo "${{ steps.quality-gate-check.outputs.project-status }}"
          echo "${{ steps.quality-gate-check.outputs.quality-gate-result }}"
